### ISSUE TITLE
UMD package generating a warning

### ISSUE THREAD

**Issue by simonfox** [dumberjs/dumber#34]
We use https://github.com/MindscapeHQ/raygun4js and in the latest release, some of the code they've bundled has a define call in it - https://www.npmjs.com/package/raygun4js/v/3.0.1?activeTab=code see dist/raygun4js.umd.js

Dumber now generates a warning when bundling this package _for module "raygun4js/dist/raygun.umd.js", more than one define calls found, skip named define rewrite._. I think I can safely ignore it, however is this something dumber should cater for or is that package not a valid umd module?

EDIT looks like it's bundling the web-vitals UMD module - so I guess this is valid UMD? In that case should dumber be generating a warning?

**Comment by 3cp** [comment]
They did something not quite right, but doesn't matter.

```js
       // AMD. Register as an anonymous module.
       define('raygun4js', function() {
            return (root.Raygun = factory());
       });
```

That's not "anonymous" module, that's a named module, the name is "raygun4js". Since the name matches the npm package name, everything is good.

Anonymous module in AMD is a define without name `define([optional-deps], function() { ...}`. Anonymous module is designed for dynamic loading. requirejs (AMD) tries to load missing module from remote, it knows the module name before fetching, hence the remote file doesn't have to supply a module name.

Most npm package builds umd/amd module using this anonymouse module format. Dumber then fills up the real module name "raygun4js" by rewriting that define line when putting this module in a bundle. Note module in a bundle is a different AMD feature than dynamic remote loading, module name is mandatory in bundle file.

Dumber warns multiple defines because there is another `define(["exports"],n)` in the code, I am not sure what does that one do. The real meat is that "skip named define rewrite".

So all good, since they used named define with correct npm package name.

**Comment by simonfox** [comment]
Cool, thanks for the explanation!
